# sudo: required
# language: generic

# services:
#   - docker

# before_install:
#   - docker build -t brianjknight/react-test -f ./client/Dockerfile.dev ./client

# script:
#   - docker run -e CI=true brianjknight/react-test npm test

# after_success:
#   - docker build -t brianjknight/multi-client ./client
#   - docker build -t brianjknight/multi-nginx ./nginx
#   - docker build -t brianjknight/multi-server ./server
#   - docker build -t brianjknight/multi-worker ./worker
#   # Log in to the docker CLI
#   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#   # Take those images and push them to docker hub
#   - docker push brianjknight/multi-client
#   - docker push brianjknight/multi-nginx
#   - docker push brianjknight/multi-server
#   - docker push brianjknight/multi-worker
